services:
  - type: web
    name: medical-chatbot-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn rag_llm_stream:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PINECONE_API_KEY
        sync: false
